config/routes.rb
Cloud::Application.routes.draw do
  # map.connect '', :controller => "default", :action => "index"
  # map.connect 'about', :controller => "default", :action => "about"
  # map.connect 'apps/:id', :controller => "apps", :action => "show", :id => /\d+/
  
  resources :reports

  root :to => 'default#index'
  match 'apps/:id' => 'apps#show', :id => /\d+/


  # map.connect ':controller/:action/:id'
  # map.connect ':controller/:action/:id/json', :format => 'json'
  # map.connect ':controller/:action/:id/', :format => 'xml'
  match ':controller(/:action(/:id))(.:format)'
  match ':controller/:action/:id/json', :format => 'json'
  match ':controller/:action/:id/xml', :format => 'xml'
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :category, :lookups, :name, :param_default, :param_name, :sql
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # before_filter :authorize, :except => [:login]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.find :all, :order => "category desc, name"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
    @records = Report.connection.execute(sprintf(@report.sql, params[:param] || @report.param_default))
    @lookups = {} 
    @report.lookups.split.each do |r|   # original lookups string sample: "id:34 name:34:id"
      a = r.split(":")
      h = Hash.new
      h[:link_field_name] = a[0]
      h[:report_id] = a[1]
      h[:param_field_name] = a[2]
      @lookups[a[0]] = h
    end if @report.lookups

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  # generate link to another report 
  # params: String, Array, Integer, Array, Hash
  def lookup(field_content, row, index, fields, lookups)
    ret = h(field_content)
#    if field_name =~ /.*:(\d+)/
#      lookup_id = $1
#      "<a href='/reports/show/#{lookup_id}?param=#{field_content}'>#{field_content}</a>"
#    else
#      field_content
#    end
    link_field_name = fields[index]
    lookup = lookups[link_field_name]
    if lookup
      param = field_content
      if lookup[:param_field_name]
        i = 0
        fields.each do |field|
          break if fields[i] == lookup[:param_field_name]
          i += 1
        end
        param = row[i]
      end
      ret = "<a href='/reports/#{lookup[:report_id]}?param=#{param}'>#{h(field_content)}</a>"
    end
    
    ret
  end
 
 end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sql %><br />
    <%= text_area 'report', 'sql', :style => "width:100%;height:100px;"  %>
  </div>
  <div class="field">
    <%= f.label :param_name %><br />
    <%= f.text_field :param_name %>
  </div>
  <div class="field">
    <%= f.label :param_default %><br />
    <%= f.text_field :param_default %>
  </div>
  <div class="field">
    <%= f.label :lookups %><br />
    <%= f.text_field :lookups %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Category</th>
    <th>Name</th>
    <th>Param</th>
    <th>default</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.id %></td>
    <td><%= report.category %></td>
    <td><%= link_to report.name, report %></td>
    <td><%= report.param_name %></td>
    <td><%= report.param_default %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<style>
    .odd {background-color: #eee;}
    td,th {padding: 4px 8px 4px 8px;}
</style>
<h1><%=@report.name%> <%="#{@report.param_name} #{params[:param] || @report.param_default}"%></h1>

<%if @records%>
    <table cellspacing=0>
      <tr>
      <%@records.fields.each do |f| %>
        <th><%= f %></th>
      <%end %>
      </tr>
    <%odd = false%>  
    <%@records.each do |r| %>
      <%odd = !odd%>
      <tr>
      <%i = 0%>
      <%r.each do |c| %>
        <td <%=odd ? "class='odd'" : nil %>><%=raw lookup(c, r, i, @records.fields, @lookups)%></td>
        <%i+=1%>
      <%end %>
      </tr>
    <% end %>
    </table>
<%end%>

<br />

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>